### PR TITLE
bump libcint and force ignore python key

### PR DESCRIPTION
**Pull request by chillenb**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chillenb** [comment]
@conda-forge-admin please rerender

**Comment by chillenb** [comment]
Oops. I learned that force ignore keys does not work the way I had hoped. Need to remove that or not all packages will get built.

**Comment by chillenb** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Because of what I outlined in #29, we cannot specify the compatible versions here but they should be defined in libcint based on ABI compatibility instead.

**Review by BastianZim — CHANGES_REQUESTED** [review]
We will have to change this upstream, if it is currently failing.

**Comment by chillenb** [comment]
Thanks for the information in #29. This whole PR shouldn't be necessary, so I'll just close it

**Pull request closed without merging**
